[package]
name = "exchange"
version = "0.1.0"
edition = "2021"

[dependencies]
arcstr = "1.2.0"
triomphe = "0.1.14"
logos = "0.15.0"
aho-corasick = "1.1.3"
strum = { version = "0.27.1", features = ["derive"]}
enum-map = "2.7.3"